apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yml
  - storageclass.yml
  - registry-configmap.yml
  - registry-secret.yml
  - registry-pvc.yml
  - registry-deployment.yml
  - ui-deployment.yml
  - registry-svc.yml
  - ui-svc.yml
  - ui-netpol.yml
  - registry-netpol.yml
  - albingress.yml