apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: ui-deployment
  name: ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui-deployment
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      containers:
      # 👇
      - image: joxit/docker-registry-ui:main
        name: ui
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi" #
          limits:
            cpu: "500m"
            memory: "128Mi"
        env:
        - name: SINGLE_REGISTRY
          value: "true"
        - name: REGISTRY_TITLE
          value: "Docker Registry UI"
        - name: DELETE_IMAGES
          value: "true"
        - name: SHOW_CONTENT_DIGEST
          value: "true"
        - name: NGINX_PROXY_PASS_URL
          value: "http://registry-svc:80"
        - name: SHOW_CATALOG_NB_TAGS
          value: "true"
        - name: CATALOG_MIN_BRANCHES
          value: "1"
        - name: CATALOG_MAX_BRANCHES
          value: "1"
        - name: TAGLIST_PAGE_SIZE
          value: "100"
        - name: REGISTRY_SECURED
          value: "false"
        - name: CATALOG_ELEMENTS_LIMIT
          value: "1000"

      # 👇 You can utilize below UI if you want
      # - image: konradkleine/docker-registry-frontend
      #   name: ui
      #   ports:
      #   - containerPort: 80
      #   resources:
      #     requests:
      #       memory: "64Mi" #
      #       cpu: "250m"
      #     limits:
      #       memory: "128Mi"
      #       cpu: "500m"
      #   env:
      #   - name: ENV_DOCKER_REGISTRY_HOST
      #     value: "registry-svc"
      #   - name: ENV_DOCKER_REGISTRY_PORT
      #     value: "80"
      #   - name: ENV_DOCKER_REGISTRY_USE_SSL
      #     value: "1"

      # 👇 You can utilize below UI if you want
      # - image: jc21/registry-ui
      #   name: ui
      #   ports:
      #   - containerPort: 80
      #   resources:
      #     requests:
      #       memory: "64Mi" #
      #       cpu: "250m"
      #     limits:
      #       memory: "128Mi"
      #       cpu: "500m"
      #   env:
      #   - name: REGISTRY_HOST
      #     value: "registry-svc"
      #   - name: REGISTRY_DOMAIN
      #     value: "registry-svc"
      #   - name: REGISTRY_STORAGE_DELETE_ENABLED
      #     value: "1"
      #   - name: REGISTRY_USER
      #     value: "ankit"
      #   - name: REGISTRY_PASS
      #     value: "jodhani"
